
=pod

PNI stands for Perl Node Interface.

=head1 Installation

To install this distro type the following:

    perl Makefile.PL
    make
    make test
    make install

=head1 Info

Point your browser to http://perl-node-interface.blogspot.com

=head1 Licence and Copyright

Copyright (C) 2009-2012, Gianluca Casati

This program is free software, you can redistribute it and/or modify it
under the same terms of the Artistic License version 2.0 .

=cut

