
=head1 NAME

PNI::Guides::Scripting

=head1 OVERVIEW

This document contains ... nothing concrete by now (:

=head1 HELLO WORLD

    use PNI::Scenario;
    my $scen = PNI::Scenario->new;

    my $node = $scen->add_node( type => 'Perlfunc::Print' );
    
    $node->in('list')->data( [ 'Hello World!', "\n" ] );

    $scen->task;

=cut

